### ISSUE TITLE
插件模式增加Dashboard菜单

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/open-monitor#419]
**描述您的需求**  
1. 建议作为插件运行的时候增加Dashboard菜单,显示内容为用户自定义并设为首页的视图
2. 如用户没有设置首页,可考虑给一个静态首页引导用户去自定义或默认给一些插件本身的监控图标

**预期行为**  
作为wecube插件运行时可以自定义首页监控页面

**Comment by pobu168** [comment]
#609
