### ISSUE TITLE
监控高可用支持

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/open-monitor#436]
**描述您的需求**  

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by zgyzgyhero** [comment]
高可用方案(双活)
双主机配置vip+keepalive，保证主机层服务高可用。
双容器应用都同时工作，保证应用高可用，共用一个数据库资源确保配置数据一致性。
监控数据分别持久化到各自本地磁盘上，保证数据高可用。 PS.因为prometheus采用pull的方式，采集频率10秒，可能会出现两个应用数据有少许区别的情况(不是同一时刻采)，问题不大。
双容器同时工作的情况下各自都会产生告警，产生的告警落库会有前后时间差，程序会识别是否重复告警，保证了告警不会重复发出。

问题点：
1、配置保存的请求只会发到其中一台机一个应用上，另一个应用无法去更新到最新配置，需要应用间同步这信息。
2、两个应用都工作所采集的数据请求也会多一倍，网络流量也会多一倍，如果都是内网环境倒没什么问题，如果是按流量计费的网络环境资源消耗会多一些。

更高级的方式：
1、数据高可用的方案以后可采用数据远端存储，采用openTSDB或influxDB等时序数据存储方案
