### ISSUE TITLE
监控对象新增表单修改

### ISSUE THREAD

**Issue by pobu168** [WeBankPartners/open-monitor#552]
**描述您的需求**  
详细设计待输出

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

更新如下：
host -> ip port
mysql -> name ip port  if_托管(agent_manager) -> mysql_user(user) mysql_passwd(password)
redis -> name ip port if_托管(agent_manager) -> redis_passwd(password)
java -> name ip port if_托管(agent_manager) -> java_user(user) java_passwd(password)
windows -> ip port
ping -> name ip 
telnet -> name ip port 
http -> name ip method url 
other -> exporter_type name ip port

**Comment by zgyzgyhero** [comment]
对象新增
host -> ip port
mysql -> name ip port  if_托管 -> mysql_user mysql_passwd
redis -> name ip port if_托管 -> redis_passwd
jmx -> name ip port if_托管 -> jmx_user jmx_passwd
ping -> name ip if_加入defalut_ping组
telnet -> name ip port if_加入defalut_telnet组
http -> name ip method url if_加入defalut_http组
other -> exporter_type name ip port
