### ISSUE TITLE
新增了指标，在对象视图中为什么不显示图像，只有默认的三个，默认的对象视图在哪里修改呢？

### ISSUE THREAD

**Issue by lifeiqiang** [WeBankPartners/open-monitor#686]
![image](https://user-images.githubusercontent.com/66341522/102045173-5b2e6500-3e13-11eb-9895-90e7c285d76a.png)

**Comment by zgyzgyhero** [comment]
对象视图现在不提供修改，如果实在要改可以在数据库里改要显示的指标，另外，新增的指标可以在自定义视图中增加视图
