### ISSUE TITLE
field update_at is not valid on table endpoint_table

### ISSUE THREAD

**Issue by nature1995** [WeBankPartners/open-monitor#746]
**描述您遇到的bug**  
请问下这个警告怎么去除呢？endpoint_table没有这个表，sh是因为endpoint_metric没有这个update_at字段吗？

**如何重现** 

**预期行为** 
没有warning

**截图**  
![image](https://user-images.githubusercontent.com/25950998/138228352-05d4df03-bc6a-4da2-aa08-c0b7da953e39.png)
![image](https://user-images.githubusercontent.com/25950998/138228449-737f6653-9572-4571-b961-10824bba7ab7.png)
![image](https://user-images.githubusercontent.com/25950998/138228756-25f8ef98-69a0-4932-a3df-5cce52a5b6b7.png)

**附加**

**Comment by zgyzgyhero** [comment]
好的，因为monitor用的还是比较老版本的xorm，下个版本会改进下db日志输出，它这warn的意思是用xorm的查询映射结果到结构体对象上，但对象定义里缺少某些字段，就是查出来的比结构体里定义的多，所以出个warn，实则没多大影响，之后我们有空会把它们一一去掉，谢谢。
